[[main]]
    identifier = "home"
    name = "首页"
    url ="/"
    weight = 10
    pre = "home"

[[main]]
    identifier = "about"
    name = "关于"
    url ="/about/"
    weight = 20
    pre = "user"

[[main]]
    identifier = "life"
    name = "消遣"
    url ="/life/"
    weight = 30
    pre = "news"

[[main]]
    identifier = "friends"
    name = "友链"
    url = "/friends/"
    weight = 40
    pre = "link"
