avatar = "https://ae01.alicdn.com/kf/HTB1DdGHXizxK1RjSspj763S.pXax.png"
subtitle = "昔日玫瑰以其名流芳，今人所持唯玫瑰之名"
description = "这里是 @Wincer，喜欢折腾新技术，却没多大耐心。个人博客会写得比较杂，包括日常吐槽、技术踩坑，偶尔会写正经一点的。欢迎订阅 RSS(•̀ᴗ•́)。"
keywords = "Blog, 博客, Web, 生活, Wincer, Linux, Dev, FreeBSD, Elixir, Python, JavaScript"

tagNumber = 36

disqusUserName = "wincer"
backendAPI = "https://api.itswincer.com/"

[StaticVendor]
    version = "wir@1.7.1"
    jsSRI = "sha256-sXV4WKJWE8CR51Da4dAmF6uFfCpLKpyb+gLMyauIG8M="

[Sitemap]
    changeFreq = "weekly"
    priority = "0.6"
    termPriority = "0.2"

[Category]
    "实验室" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/laboratory.jpg"
    "博客栈" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/bo-inn.jpg"
    "分享境" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/share.jpg"
    "碎碎念" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/thoughts.jpg"
    "文字阁" = "https://cdn.jsdelivr.net/npm/wir@1.1.0/cate-cover/letter.jpg"


[[social]]
    icon = "twitter"
    url = "https://twitter.com/wincer_chan"

[[social]]
    icon = "github"
    url = "https://github.com/WincerChan"

[[social]]
    icon = "telegram"
    url = "https://t.me/Tivsae"
