#!/usr/bin/env node

const CryptoJS = require("crypto-js");
const cheerio = require("cheerio");
const fs = require("fs")
const needCryptBlogSlugs = [
    "d67271d8"
]

needCryptBlogSlugs.forEach(slug => {
    let html = fs.readFileSync(`public/posts/${slug}/index.html`).toString()
    const $ = cheerio.load(html);
    const cipherText = CryptoJS.AES.encrypt($("content").html(), $("content").data("password")).toString()
    $("content").html(cipherText);
    $("content").removeAttr("data-password");
    fs.writeFileSync(`public/posts/${slug}/index.html`, $.html());
})